App\DataTransferObject\CartToOrderDTO:
  properties:
    address:
      - NotBlank: ~
      - Type: string
    phoneNumber:
      - NotBlank: ~
      - Type: string
    comment:
      - Type: string
    userId:
      - Type: integer

App\Entity\Product:
  properties:
    id:
      - Type: integer