SimpleSeller\CoreBundle\Entity\Category:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: ['category', 'product', 'orderItem']
    name:
      expose: true
      groups: ['category', 'product', 'productByCategory']
    products:
      expose: true
      groups: ['category']